-- ============================================================
-- 探海灵眸 SeaSight - 领域资产认知智能体演示数据
-- ------------------------------------------------------------
-- 用途：为比赛演示补齐知识资产、本体版本、决策轨迹和证据链。
-- 特性：
--   1. 仅写入知识域表，不修改设备、事件、工单、轨迹和报表数据。
--   2. 所有业务编号固定，配合 ON CONFLICT DO NOTHING 可重复执行。
--   3. 资产和决策均带 DEMO 标记，避免把演示样本误认为生产事实。
--   4. 生产环境不会自动执行本文件，需要显式执行演示种子命令。
-- ============================================================

BEGIN;

-- ---------- 多模态知识资产 ----------
INSERT INTO t_knowledge_asset (
    asset_id,
    asset_type,
    title,
    description,
    source_uri,
    source_system,
    mime_type,
    region,
    township,
    security_level,
    status,
    current_version,
    standard_codes,
    tags,
    attributes_json,
    created_by,
    updated_by,
    created_at,
    updated_at
) VALUES
(
    'KA-DEMO-POLICY-001',
    'document',
    '连江县海漂垃圾巡查处置指南（演示样本）',
    '演示连江海漂垃圾从发现、巡查、打捞到回收处置的证据留痕流程。',
    'demo://lianjiang/knowledge/marine-litter-response-guide',
    '演示数据',
    'text/markdown',
    '连江县',
    NULL,
    'internal',
    'active',
    1,
    '["DEMO-LJ-HP-2026"]'::jsonb,
    '["DEMO","海漂垃圾","巡查处置","决策依据"]'::jsonb,
    '{"demo":true,"document_class":"操作规程","retention_years":5}'::jsonb,
    'admin',
    'admin',
    now() - interval '32 days',
    now() - interval '3 days'
),
(
    'KA-DEMO-MONITOR-001',
    'table',
    '马鼻镇海漂垃圾监测汇总（演示）',
    '马鼻镇近 24 小时海漂垃圾类型、数量和平均置信度汇总。',
    'demo://lianjiang/knowledge/mabi-marine-litter-summary',
    '演示数据',
    'application/json',
    '连江县',
    '马鼻镇',
    'internal',
    'active',
    1,
    '["DEMO-LJ-HP-2026"]'::jsonb,
    '["DEMO","马鼻镇","监测汇总","泡沫垃圾"]'::jsonb,
    '{"demo":true,"aggregation_window":"24h","unit":"件"}'::jsonb,
    'operator',
    'operator',
    now() - interval '8 days',
    now() - interval '2 days'
),
(
    'KA-DEMO-IMAGE-001',
    'image',
    '黄岐渔港泡沫垃圾识别记录（演示）',
    '黄岐渔港岸线摄像头演示识别帧，包含泡沫垃圾与疑似废弃渔具标注。',
    'demo://lianjiang/knowledge/huangqi-foam-detection-frame',
    '演示数据',
    'image/jpeg',
    '连江县',
    '黄岐镇',
    'internal',
    'active',
    1,
    '["DEMO-LJ-HP-2026"]'::jsonb,
    '["DEMO","黄岐渔港","图像识别","废弃渔具"]'::jsonb,
    '{"demo":true,"camera_id":"CAM-HUANGQI-01","annotated":true}'::jsonb,
    'operator',
    'operator',
    now() - interval '7 days',
    now() - interval '1 day'
),
(
    'KA-DEMO-DATASET-001',
    'dataset',
    '连江岸线多模态训练集 v1（演示）',
    '面向岸线巡查场景的图文与遥测联合样本，用于说明低资源数据资产组织方式。',
    'demo://lianjiang/knowledge/coast-multimodal-dataset-v1',
    '演示数据',
    'application/x-ndjson',
    '连江县',
    NULL,
    'restricted',
    'active',
    1,
    '["DEMO-LJ-HP-2026","DEMO-ML-DATA-01"]'::jsonb,
    '["DEMO","多模态","训练集","无人机巡查"]'::jsonb,
    '{"demo":true,"schema_version":"1.0","modalities":["text","image","telemetry"]}'::jsonb,
    'admin',
    'admin',
    now() - interval '20 days',
    now() - interval '4 days'
),
(
    'KA-DEMO-EVENT-001',
    'event',
    '马鼻镇泡沫塑料聚集事件（演示）',
    '演示事件记录：马鼻镇岸线发现泡沫塑料聚集并触发巡查与打捞任务。',
    'demo://lianjiang/knowledge/mabi-foam-event',
    '演示数据',
    'application/json',
    '连江县',
    '马鼻镇',
    'internal',
    'active',
    1,
    '["DEMO-LJ-HP-2026"]'::jsonb,
    '["DEMO","马鼻镇","泡沫塑料","事件"]'::jsonb,
    '{"demo":true,"event_level":"attention","linked_asset":"evt_demo_0005"}'::jsonb,
    'operator',
    'operator',
    now() - interval '6 days',
    now() - interval '6 hours'
),
(
    'KA-DEMO-TELEMETRY-001',
    'telemetry',
    '黄岐渔港风浪与潮汐遥测记录（演示）',
    '演示潮汐、风向和风速时序数据，用于解释漂浮垃圾漂移和作业窗口。',
    'demo://lianjiang/knowledge/huangqi-hydro-meteorology',
    '演示数据',
    'application/json',
    '连江县',
    '黄岐镇',
    'internal',
    'active',
    1,
    '["DEMO-LJ-HP-2026"]'::jsonb,
    '["DEMO","黄岐渔港","潮汐","风向"]'::jsonb,
    '{"demo":true,"sample_interval_minutes":10,"quality":"simulated"}'::jsonb,
    'approver',
    'approver',
    now() - interval '5 days',
    now() - interval '12 hours'
)
ON CONFLICT (asset_id) DO NOTHING;

-- ---------- 资产内容版本 ----------
INSERT INTO t_knowledge_asset_version (
    version_id,
    asset_id,
    version_no,
    status,
    content_hash,
    content_text,
    content_json,
    extraction_method,
    extraction_confidence,
    language,
    valid_from,
    valid_to,
    metadata_json,
    created_by,
    created_at
) VALUES
(
    'KAV-DEMO-POLICY-001-V1',
    'KA-DEMO-POLICY-001',
    1,
    'active',
    md5('KA-DEMO-POLICY-001|v1|连江县海漂垃圾巡查处置指南'),
    '连江县海漂垃圾巡查处置演示流程：海漂垃圾包括泡沫垃圾、泡沫塑料和废弃渔具等类型。发现泡沫塑料聚集后，责任区域应启动岸线巡查，核实位置、范围和漂移方向，再生成打捞任务。打捞任务完成后进入回收处置环节。马鼻镇和黄岐渔港应记录潮汐、风向和风速，作为判断漂浮垃圾来源、漂移路径和作业窗口的证据。所有结论必须保留资产版本、原始引用和审核人。',
    '{"sections":[{"title":"发现与巡查","order":1},{"title":"任务生成","order":2},{"title":"回收处置","order":3},{"title":"证据留痕","order":4}]}'::jsonb,
    'manual',
    0.9800,
    'zh-CN',
    now() - interval '32 days',
    NULL,
    '{"demo":true,"review_status":"published"}'::jsonb,
    'admin',
    now() - interval '32 days'
),
(
    'KAV-DEMO-MONITOR-001-V1',
    'KA-DEMO-MONITOR-001',
    1,
    'active',
    md5('KA-DEMO-MONITOR-001|v1|马鼻镇监测汇总'),
    '马鼻镇近 24 小时演示监测汇总：泡沫垃圾 14 件，泡沫塑料 10.8 千克，废弃渔具 4 件；高发点位集中在马鼻码头近岸。建议对泡沫类漂浮物执行优先巡查和打捞，并复核潮汐与风向数据。',
    '{"township":"马鼻镇","window":"24h","rows":[{"class":"泡沫垃圾","count":14,"weight_kg":10.8},{"class":"废弃渔具","count":4,"weight_kg":6.2}],"hotspot":"马鼻码头近岸"}'::jsonb,
    'table_parse',
    0.9600,
    'zh-CN',
    now() - interval '8 days',
    NULL,
    '{"demo":true,"source_rows":2,"quality":"simulated"}'::jsonb,
    'operator',
    now() - interval '8 days'
),
(
    'KAV-DEMO-IMAGE-001-V1',
    'KA-DEMO-IMAGE-001',
    1,
    'active',
    md5('KA-DEMO-IMAGE-001|v1|黄岐渔港识别记录'),
    '黄岐渔港演示识别帧：检出泡沫垃圾 6 处、疑似废弃渔具 2 处，画面质量良好。用于说明图像资产如何登记检测框、置信度和人工复核状态。',
    '{"camera_id":"CAM-HUANGQI-01","captured_at":"2026-09-18T16:20:00+08:00","detections":[{"class":"泡沫垃圾","count":6,"confidence":0.93},{"class":"废弃渔具","count":2,"confidence":0.84}],"review_status":"confirmed"}'::jsonb,
    'vision_model',
    0.9100,
    'zh-CN',
    now() - interval '7 days',
    NULL,
    '{"demo":true,"model":"yolo-world-v2","human_reviewed":true}'::jsonb,
    'operator',
    now() - interval '7 days'
),
(
    'KAV-DEMO-DATASET-001-V1',
    'KA-DEMO-DATASET-001',
    1,
    'active',
    md5('KA-DEMO-DATASET-001|v1|多模态训练集'),
    '连江岸线多模态训练集演示版本包含岸线照片、表格汇总和遥测时序，可用于无人机巡查、泡沫垃圾识别和废弃渔具识别的低资源迁移实验。样本均已脱敏并保留来源说明。',
    '{"schema_version":"1.0","samples":1280,"modalities":{"image":860,"text":280,"telemetry":140},"labels":["泡沫垃圾","泡沫塑料","废弃渔具","岸线巡查","无人机巡查"]}'::jsonb,
    'dataset_manifest',
    0.9400,
    'zh-CN',
    now() - interval '20 days',
    NULL,
    '{"demo":true,"split":{"train":896,"validation":256,"test":128}}'::jsonb,
    'admin',
    now() - interval '20 days'
),
(
    'KAV-DEMO-EVENT-001-V1',
    'KA-DEMO-EVENT-001',
    1,
    'active',
    md5('KA-DEMO-EVENT-001|v1|马鼻镇事件'),
    '演示事件：马鼻镇岸线发现泡沫塑料聚集，最大连续面积约 18 平方米，事件触发岸线巡查，已关联打捞任务和回收处置记录。',
    '{"event_id":"evt_demo_0005","township":"马鼻镇","main_class":"泡沫塑料","det_count":7,"max_confidence":0.93,"status":"resolved","next_action":"生成打捞任务"}'::jsonb,
    'event_bridge',
    0.9700,
    'zh-CN',
    now() - interval '6 days',
    NULL,
    '{"demo":true,"linked_task":"tsk_demo_0001"}'::jsonb,
    'operator',
    now() - interval '6 days'
),
(
    'KAV-DEMO-TELEMETRY-001-V1',
    'KA-DEMO-TELEMETRY-001',
    1,
    'active',
    md5('KA-DEMO-TELEMETRY-001|v1|黄岐渔港遥测'),
    '黄岐渔港演示遥测：未来 6 小时潮位由 0.8 米升至 2.1 米，风向东南，平均风速 4.2 米每秒。潮汐和风向可能推动泡沫垃圾向渔港西侧岸线聚集，建议在涨潮前完成巡查。',
    '{"location":"黄岐渔港","readings":[{"hour":0,"tide_m":0.8,"wind_direction":"东南","wind_speed_mps":4.2},{"hour":3,"tide_m":1.6,"wind_direction":"东南","wind_speed_mps":5.1},{"hour":6,"tide_m":2.1,"wind_direction":"南","wind_speed_mps":4.8}]}'::jsonb,
    'sensor_import',
    0.9000,
    'zh-CN',
    now() - interval '5 days',
    NULL,
    '{"demo":true,"quality":"simulated","calibration":"not_applicable"}'::jsonb,
    'approver',
    now() - interval '5 days'
)
ON CONFLICT (version_id) DO NOTHING;

-- ---------- 已发布本体 v1 ----------
INSERT INTO t_ontology_version (
    version_id,
    name,
    version_no,
    status,
    parent_version_id,
    description,
    standard_codes,
    metadata_json,
    created_by,
    reviewed_by,
    reviewed_at,
    published_by,
    published_at,
    created_at,
    updated_at
) VALUES
(
    'ONT-DEMO-MARINE-001',
    '连江海漂垃圾治理领域本体',
    1,
    'published',
    NULL,
    '覆盖垃圾类型、责任区域、巡查流程、打捞处置和环境影响因素的演示本体。',
    '["DEMO-LJ-HP-2026","DEMO-ML-DATA-01"]'::jsonb,
    '{"demo":true,"domain":"海漂垃圾治理","node_count":12,"relation_count":15}'::jsonb,
    'admin',
    'approver',
    now() - interval '28 days',
    'admin',
    now() - interval '27 days',
    now() - interval '30 days',
    now() - interval '27 days'
),
(
    'ONT-DEMO-MARINE-002',
    '连江海漂垃圾治理领域本体',
    2,
    'in_review',
    'ONT-DEMO-MARINE-001',
    '增加热区预警、生态敏感岸段和处置时限的候选本体，等待人工审核。',
    '["DEMO-LJ-HP-2026","DEMO-ML-DATA-01","DEMO-RISK-2026"]'::jsonb,
    '{"demo":true,"change_request":"增加风险分级和时限约束","proposal_source":"operator"}'::jsonb,
    'operator',
    NULL,
    NULL,
    NULL,
    NULL,
    now() - interval '1 day',
    now() - interval '1 day'
)
ON CONFLICT (version_id) DO NOTHING;

-- ---------- 已发布本体节点 ----------
INSERT INTO t_ontology_node (
    node_id,
    ontology_version_id,
    entity_type,
    name,
    canonical_name,
    description,
    aliases,
    properties_json,
    source_asset_id,
    source_version_id,
    confidence,
    review_status,
    reviewed_by,
    reviewed_at,
    created_at
) VALUES
(
    'NODE-DEMO-LITTER',
    'ONT-DEMO-MARINE-001',
    'domain_entity',
    '海漂垃圾',
    '海漂垃圾',
    '海上漂浮并可能漂移上岸或进入港区的垃圾总称。',
    '["海洋垃圾","漂浮垃圾"]'::jsonb,
    '{"scope":"domain"}'::jsonb,
    'KA-DEMO-POLICY-001',
    'KAV-DEMO-POLICY-001-V1',
    0.9800,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'NODE-DEMO-FOAM',
    'ONT-DEMO-MARINE-001',
    'waste_type',
    '泡沫垃圾',
    '泡沫垃圾',
    '泡沫类海漂垃圾，重点包括泡沫箱碎块和泡沫塑料漂浮物。',
    '["泡沫漂浮物","泡沫碎块"]'::jsonb,
    '{"priority":"high","bin":"foam"}'::jsonb,
    'KA-DEMO-MONITOR-001',
    'KAV-DEMO-MONITOR-001-V1',
    0.9700,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'NODE-DEMO-EPS',
    'ONT-DEMO-MARINE-001',
    'material',
    '泡沫塑料',
    '泡沫塑料',
    '常见于渔获保鲜箱和包装材料的轻质塑料，破碎后易扩散。',
    '["EPS","聚苯乙烯泡沫"]'::jsonb,
    '{"material":"expanded_polystyrene"}'::jsonb,
    'KA-DEMO-EVENT-001',
    'KAV-DEMO-EVENT-001-V1',
    0.9600,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'NODE-DEMO-GEAR',
    'ONT-DEMO-MARINE-001',
    'waste_type',
    '废弃渔具',
    '废弃渔具',
    '破损渔网、绳索、浮标和其他失去使用价值的渔业器具。',
    '["废旧渔网","渔具垃圾"]'::jsonb,
    '{"priority":"high","bin":"plastic"}'::jsonb,
    'KA-DEMO-IMAGE-001',
    'KAV-DEMO-IMAGE-001-V1',
    0.9600,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'NODE-DEMO-PATROL',
    'ONT-DEMO-MARINE-001',
    'process',
    '岸线巡查',
    '岸线巡查',
    '沿责任岸线核验垃圾位置、类型、范围和漂移趋势的处置活动。',
    '["海岸巡查","沿线核查"]'::jsonb,
    '{"sla_hours":2,"evidence_required":true}'::jsonb,
    'KA-DEMO-POLICY-001',
    'KAV-DEMO-POLICY-001-V1',
    0.9700,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'NODE-DEMO-COLLECT',
    'ONT-DEMO-MARINE-001',
    'process',
    '打捞任务',
    '打捞任务',
    '根据巡查证据安排水面机器人或人工完成的垃圾打捞工单。',
    '["清理任务","水面打捞"]'::jsonb,
    '{"assignee":"robot_or_manual","priority":1}'::jsonb,
    'KA-DEMO-EVENT-001',
    'KAV-DEMO-EVENT-001-V1',
    0.9700,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'NODE-DEMO-RECYCLE',
    'ONT-DEMO-MARINE-001',
    'process',
    '回收处置',
    '回收处置',
    '打捞物分类称重、暂存、转运和合规回收的后续流程。',
    '["分类回收","合规处置"]'::jsonb,
    '{"requires_weight":true,"requires_review":true}'::jsonb,
    'KA-DEMO-POLICY-001',
    'KAV-DEMO-POLICY-001-V1',
    0.9500,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'NODE-DEMO-MABI',
    'ONT-DEMO-MARINE-001',
    'region',
    '马鼻镇',
    '马鼻镇',
    '连江县沿海责任区域之一，码头近岸为演示高发点位。',
    '["马鼻"]'::jsonb,
    '{"county":"连江县","coast_priority":"high"}'::jsonb,
    'KA-DEMO-EVENT-001',
    'KAV-DEMO-EVENT-001-V1',
    0.9900,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'NODE-DEMO-HUANGQI',
    'ONT-DEMO-MARINE-001',
    'region',
    '黄岐渔港',
    '黄岐渔港',
    '连江县重点渔港区域，需关注渔具类垃圾和潮汐带来的漂浮物聚集。',
    '["黄岐"]'::jsonb,
    '{"county":"连江县","port_type":"fishing"}'::jsonb,
    'KA-DEMO-IMAGE-001',
    'KAV-DEMO-IMAGE-001-V1',
    0.9900,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'NODE-DEMO-TIDE',
    'ONT-DEMO-MARINE-001',
    'environmental_factor',
    '潮汐',
    '潮汐',
    '周期性水位变化，会影响漂浮垃圾向岸线和港区聚集。',
    '["潮位","涨潮"]'::jsonb,
    '{"unit":"m","source":"hydro_meteorology"}'::jsonb,
    'KA-DEMO-TELEMETRY-001',
    'KAV-DEMO-TELEMETRY-001-V1',
    0.9300,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'NODE-DEMO-WIND',
    'ONT-DEMO-MARINE-001',
    'environmental_factor',
    '风向',
    '风向',
    '近海风场方向，可用于解释漂浮垃圾的短期漂移趋势。',
    '["风场","海风"]'::jsonb,
    '{"unit":"direction","source":"hydro_meteorology"}'::jsonb,
    'KA-DEMO-TELEMETRY-001',
    'KAV-DEMO-TELEMETRY-001-V1',
    0.9300,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'NODE-DEMO-UAV',
    'ONT-DEMO-MARINE-001',
    'equipment',
    '无人机巡查',
    '无人机巡查',
    '使用无人机对岸线、近岸和船舶难以到达区域进行快速视觉巡查。',
    '["UAV巡查","空中巡查"]'::jsonb,
    '{"device_type":"drone","asset_type":"multimodal"}'::jsonb,
    'KA-DEMO-DATASET-001',
    'KAV-DEMO-DATASET-001-V1',
    0.9200,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
)
ON CONFLICT (node_id) DO NOTHING;

-- ---------- 已发布本体关系 ----------
INSERT INTO t_ontology_relation (
    relation_id,
    ontology_version_id,
    source_node_id,
    target_node_id,
    relation_type,
    description,
    properties_json,
    evidence_json,
    confidence,
    review_status,
    reviewed_by,
    reviewed_at,
    created_at
) VALUES
(
    'REL-DEMO-001',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-LITTER',
    'NODE-DEMO-FOAM',
    '包含类型',
    '海漂垃圾包含泡沫垃圾。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-POLICY-001","version_id":"KAV-DEMO-POLICY-001-V1","quote":"海漂垃圾包括泡沫垃圾"}]'::jsonb,
    0.9700,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'REL-DEMO-002',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-LITTER',
    'NODE-DEMO-GEAR',
    '包含类型',
    '海漂垃圾包含废弃渔具。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-POLICY-001","version_id":"KAV-DEMO-POLICY-001-V1","quote":"海漂垃圾包括废弃渔具"}]'::jsonb,
    0.9600,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'REL-DEMO-003',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-FOAM',
    'NODE-DEMO-EPS',
    '来源',
    '泡沫垃圾的主要来源之一是泡沫塑料。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-EVENT-001","version_id":"KAV-DEMO-EVENT-001-V1","quote":"泡沫塑料聚集"}]'::jsonb,
    0.9400,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'REL-DEMO-004',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-FOAM',
    'NODE-DEMO-MABI',
    '位于',
    '演示高发位置为马鼻镇近岸。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-MONITOR-001","version_id":"KAV-DEMO-MONITOR-001-V1","quote":"马鼻码头近岸"}]'::jsonb,
    0.9500,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'REL-DEMO-005',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-GEAR',
    'NODE-DEMO-HUANGQI',
    '位于',
    '黄岐渔港存在废弃渔具识别记录。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-IMAGE-001","version_id":"KAV-DEMO-IMAGE-001-V1","quote":"疑似废弃渔具"}]'::jsonb,
    0.9500,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'REL-DEMO-006',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-FOAM',
    'NODE-DEMO-PATROL',
    '触发',
    '发现泡沫垃圾或泡沫塑料聚集时触发岸线巡查。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-POLICY-001","version_id":"KAV-DEMO-POLICY-001-V1","quote":"发现泡沫塑料聚集后启动岸线巡查"}]'::jsonb,
    0.9700,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'REL-DEMO-007',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-GEAR',
    'NODE-DEMO-PATROL',
    '触发',
    '发现废弃渔具时触发岸线巡查。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-IMAGE-001","version_id":"KAV-DEMO-IMAGE-001-V1","quote":"疑似废弃渔具"}]'::jsonb,
    0.9400,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'REL-DEMO-008',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-PATROL',
    'NODE-DEMO-COLLECT',
    '生成',
    '岸线巡查核实后生成打捞任务。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-EVENT-001","version_id":"KAV-DEMO-EVENT-001-V1","quote":"生成打捞任务"}]'::jsonb,
    0.9700,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'REL-DEMO-009',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-COLLECT',
    'NODE-DEMO-RECYCLE',
    '处置方式',
    '打捞任务完成后进入回收处置。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-POLICY-001","version_id":"KAV-DEMO-POLICY-001-V1","quote":"打捞任务完成后进入回收处置"}]'::jsonb,
    0.9600,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'REL-DEMO-010',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-MABI',
    'NODE-DEMO-PATROL',
    '责任区域',
    '马鼻镇承担本区域岸线巡查责任。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-EVENT-001","version_id":"KAV-DEMO-EVENT-001-V1","quote":"马鼻镇岸线"}]'::jsonb,
    0.9300,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'REL-DEMO-011',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-HUANGQI',
    'NODE-DEMO-PATROL',
    '责任区域',
    '黄岐渔港承担港区岸线巡查责任。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-IMAGE-001","version_id":"KAV-DEMO-IMAGE-001-V1","quote":"黄岐渔港岸线"}]'::jsonb,
    0.9300,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'REL-DEMO-012',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-TIDE',
    'NODE-DEMO-FOAM',
    '影响',
    '潮汐会影响泡沫垃圾向岸线和港区聚集。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-TELEMETRY-001","version_id":"KAV-DEMO-TELEMETRY-001-V1","quote":"潮位由 0.8 米升至 2.1 米"}]'::jsonb,
    0.9200,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'REL-DEMO-013',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-WIND',
    'NODE-DEMO-FOAM',
    '影响',
    '风向会影响泡沫垃圾的短期漂移方向。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-TELEMETRY-001","version_id":"KAV-DEMO-TELEMETRY-001-V1","quote":"风向东南"}]'::jsonb,
    0.9200,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'REL-DEMO-014',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-TIDE',
    'NODE-DEMO-COLLECT',
    '影响',
    '潮汐窗口影响打捞任务安排。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-TELEMETRY-001","version_id":"KAV-DEMO-TELEMETRY-001-V1","quote":"建议在涨潮前完成巡查"}]'::jsonb,
    0.9000,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
),
(
    'REL-DEMO-015',
    'ONT-DEMO-MARINE-001',
    'NODE-DEMO-PATROL',
    'NODE-DEMO-UAV',
    '使用的设备',
    '岸线巡查可使用无人机扩大覆盖范围。',
    '{}'::jsonb,
    '[{"asset_id":"KA-DEMO-DATASET-001","version_id":"KAV-DEMO-DATASET-001-V1","quote":"无人机巡查"}]'::jsonb,
    0.9100,
    'approved',
    'approver',
    now() - interval '28 days',
    now() - interval '30 days'
)
ON CONFLICT (relation_id) DO NOTHING;

-- ---------- 审核中的本体 v2（展示动态演化） ----------
INSERT INTO t_ontology_node (
    node_id,
    ontology_version_id,
    entity_type,
    name,
    canonical_name,
    description,
    aliases,
    properties_json,
    source_asset_id,
    source_version_id,
    confidence,
    review_status,
    reviewed_by,
    reviewed_at,
    created_at
) VALUES
(
    'NODE-DEMO-HOTSPOT',
    'ONT-DEMO-MARINE-002',
    'risk_concept',
    '海漂垃圾热区',
    '海漂垃圾热区',
    '短时间内重复出现同类垃圾或数量超过阈值的区域。',
    '["垃圾热区","高发区域"]'::jsonb,
    '{"threshold":"3 events / 24h","status":"candidate"}'::jsonb,
    'KA-DEMO-MONITOR-001',
    'KAV-DEMO-MONITOR-001-V1',
    0.7800,
    'proposed',
    NULL,
    NULL,
    now() - interval '23 hours'
),
(
    'NODE-DEMO-FLOATING',
    'ONT-DEMO-MARINE-002',
    'observation',
    '黄岐渔港漂浮物',
    '黄岐渔港漂浮物',
    '黄岐渔港图像中检出的可漂浮垃圾集合。',
    '["港区漂浮物"]'::jsonb,
    '{"source":"vision","candidate":true}'::jsonb,
    'KA-DEMO-IMAGE-001',
    'KAV-DEMO-IMAGE-001-V1',
    0.7500,
    'proposed',
    NULL,
    NULL,
    now() - interval '23 hours'
),
(
    'NODE-DEMO-ECO',
    'ONT-DEMO-MARINE-002',
    'region',
    '生态敏感岸段',
    '生态敏感岸段',
    '生态价值较高、需要优先清理和限制干扰的岸段。',
    '["敏感岸线"]'::jsonb,
    '{"candidate":true}'::jsonb,
    'KA-DEMO-DATASET-001',
    'KAV-DEMO-DATASET-001-V1',
    0.7100,
    'proposed',
    NULL,
    NULL,
    now() - interval '23 hours'
),
(
    'NODE-DEMO-SLA',
    'ONT-DEMO-MARINE-002',
    'rule',
    '处置时限',
    '处置时限',
    '不同风险等级对应不同的巡查、打捞和复核完成时长。',
    '["响应时限"]'::jsonb,
    '{"risk_levels":["high","normal"],"candidate":true}'::jsonb,
    'KA-DEMO-POLICY-001',
    'KAV-DEMO-POLICY-001-V1',
    0.7000,
    'proposed',
    NULL,
    NULL,
    now() - interval '23 hours'
),
(
    'NODE-DEMO-V2-FOAM',
    'ONT-DEMO-MARINE-002',
    'waste_type',
    '泡沫垃圾',
    '泡沫垃圾',
    '泡沫类海漂垃圾，作为热区形成与漂移分析的候选对象。',
    '["泡沫漂浮物","泡沫碎块"]'::jsonb,
    '{"priority":"high","candidate":true}'::jsonb,
    'KA-DEMO-MONITOR-001',
    'KAV-DEMO-MONITOR-001-V1',
    0.7900,
    'proposed',
    NULL,
    NULL,
    now() - interval '23 hours'
),
(
    'NODE-DEMO-V2-HUANGQI',
    'ONT-DEMO-MARINE-002',
    'region',
    '黄岐渔港',
    '黄岐渔港',
    '连江县重点渔港区域，作为港区漂浮物和生态敏感岸段的候选关联区域。',
    '["黄岐"]'::jsonb,
    '{"county":"连江县","port_type":"fishing","candidate":true}'::jsonb,
    'KA-DEMO-IMAGE-001',
    'KAV-DEMO-IMAGE-001-V1',
    0.8000,
    'proposed',
    NULL,
    NULL,
    now() - interval '23 hours'
)
ON CONFLICT (node_id) DO NOTHING;

INSERT INTO t_ontology_relation (
    relation_id,
    ontology_version_id,
    source_node_id,
    target_node_id,
    relation_type,
    description,
    properties_json,
    evidence_json,
    confidence,
    review_status,
    reviewed_by,
    reviewed_at,
    created_at
) VALUES
(
    'REL-DEMO-V2-001',
    'ONT-DEMO-MARINE-002',
    'NODE-DEMO-V2-FOAM',
    'NODE-DEMO-HOTSPOT',
    '形成',
    '重复出现的泡沫垃圾可形成海漂垃圾热区。',
    '{"candidate":true}'::jsonb,
    '[{"asset_id":"KA-DEMO-MONITOR-001","version_id":"KAV-DEMO-MONITOR-001-V1"}]'::jsonb,
    0.7600,
    'proposed',
    NULL,
    NULL,
    now() - interval '23 hours'
),
(
    'REL-DEMO-V2-002',
    'ONT-DEMO-MARINE-002',
    'NODE-DEMO-FLOATING',
    'NODE-DEMO-V2-HUANGQI',
    '位于',
    '黄岐渔港漂浮物位于黄岐渔港区域。',
    '{"candidate":true}'::jsonb,
    '[{"asset_id":"KA-DEMO-IMAGE-001","version_id":"KAV-DEMO-IMAGE-001-V1"}]'::jsonb,
    0.7500,
    'proposed',
    NULL,
    NULL,
    now() - interval '23 hours'
),
(
    'REL-DEMO-V2-003',
    'ONT-DEMO-MARINE-002',
    'NODE-DEMO-HOTSPOT',
    'NODE-DEMO-SLA',
    '约束',
    '热区风险等级约束巡查和处置时限。',
    '{"candidate":true}'::jsonb,
    '[{"asset_id":"KA-DEMO-POLICY-001","version_id":"KAV-DEMO-POLICY-001-V1"}]'::jsonb,
    0.7100,
    'proposed',
    NULL,
    NULL,
    now() - interval '23 hours'
)
ON CONFLICT (relation_id) DO NOTHING;

-- ---------- 决策轨迹 ----------
INSERT INTO t_decision_trace (
    trace_id,
    run_id,
    question,
    answer_summary,
    status,
    ontology_version_id,
    policy_version,
    metadata_json,
    created_by,
    created_at
) VALUES
(
    'DEC-DEMO-001',
    NULL,
    '马鼻镇发现泡沫塑料聚集后，应当如何安排巡查与打捞处置？',
    '先由马鼻镇岸线巡查核验范围，再生成打捞任务；泡沫类垃圾按回收处置路径执行，并结合潮汐与风向记录漂移依据。',
    'completed',
    'ONT-DEMO-MARINE-001',
    'DEMO-POLICY-2026.1',
    '{"demo":true,"scenario":"mabi_foam_priority","review_required":false}'::jsonb,
    'operator',
    now() - interval '5 days'
),
(
    'DEC-DEMO-002',
    NULL,
    '黄岐渔港出现废弃渔具，应安排哪个处置流程？',
    '将废弃渔具归入高风险海漂垃圾，先执行港区岸线巡查，再生成打捞任务，打捞后进入分类回收处置。',
    'completed',
    'ONT-DEMO-MARINE-001',
    'DEMO-POLICY-2026.1',
    '{"demo":true,"scenario":"huangqi_fishing_gear","review_required":true}'::jsonb,
    'admin',
    now() - interval '3 days'
),
(
    'DEC-DEMO-003',
    NULL,
    '黄岐渔港夜间无人值守期间，废弃渔具是否会在两小时内漂入航道？',
    '现有演示数据缺少连续夜间视频和水流实测，系统不给出确定性结论，建议补采证据后重新评估。',
    'insufficient_evidence',
    'ONT-DEMO-MARINE-001',
    'DEMO-POLICY-2026.1',
    '{"demo":true,"scenario":"night_current_gap","missing_evidence":["夜间视频","连续流速"]}'::jsonb,
    'approver',
    now() - interval '1 day'
)
ON CONFLICT (trace_id) DO NOTHING;

-- ---------- 决策证据链 ----------
INSERT INTO t_decision_evidence (
    evidence_id,
    trace_id,
    rank_no,
    asset_id,
    asset_version_id,
    node_id,
    relation_id,
    hop_no,
    citation_text,
    source_uri,
    score,
    metadata_json,
    created_at
) VALUES
(
    'EVD-DEMO-001-01',
    'DEC-DEMO-001',
    1,
    'KA-DEMO-POLICY-001',
    'KAV-DEMO-POLICY-001-V1',
    'NODE-DEMO-FOAM',
    'REL-DEMO-006',
    1,
    '演示指南规定：发现泡沫塑料聚集后启动岸线巡查，核实位置、范围和漂移方向。',
    'demo://lianjiang/knowledge/marine-litter-response-guide',
    9.800000,
    '{"demo":true,"quote_type":"policy"}'::jsonb,
    now() - interval '5 days'
),
(
    'EVD-DEMO-001-02',
    'DEC-DEMO-001',
    2,
    'KA-DEMO-EVENT-001',
    'KAV-DEMO-EVENT-001-V1',
    'NODE-DEMO-MABI',
    'REL-DEMO-004',
    1,
    '马鼻镇泡沫塑料聚集事件已记录 7 处目标，最高检测置信度 0.93，状态为已处置。',
    'demo://lianjiang/knowledge/mabi-foam-event',
    9.100000,
    '{"demo":true,"quote_type":"event"}'::jsonb,
    now() - interval '5 days'
),
(
    'EVD-DEMO-001-03',
    'DEC-DEMO-001',
    3,
    'KA-DEMO-MONITOR-001',
    'KAV-DEMO-MONITOR-001-V1',
    'NODE-DEMO-FOAM',
    'REL-DEMO-004',
    1,
    '马鼻镇近 24 小时监测汇总显示泡沫垃圾 14 件，是当前演示数据中的主要类别。',
    'demo://lianjiang/knowledge/mabi-marine-litter-summary',
    8.700000,
    '{"demo":true,"quote_type":"table"}'::jsonb,
    now() - interval '5 days'
),
(
    'EVD-DEMO-001-04',
    'DEC-DEMO-001',
    4,
    'KA-DEMO-TELEMETRY-001',
    'KAV-DEMO-TELEMETRY-001-V1',
    'NODE-DEMO-WIND',
    'REL-DEMO-013',
    2,
    '演示遥测记录东南风和 4.2 米每秒平均风速，可用于判断泡沫垃圾的短期漂移趋势。',
    'demo://lianjiang/knowledge/huangqi-hydro-meteorology',
    7.900000,
    '{"demo":true,"quote_type":"telemetry"}'::jsonb,
    now() - interval '5 days'
),
(
    'EVD-DEMO-002-01',
    'DEC-DEMO-002',
    1,
    'KA-DEMO-IMAGE-001',
    'KAV-DEMO-IMAGE-001-V1',
    'NODE-DEMO-GEAR',
    'REL-DEMO-005',
    0,
    '黄岐渔港演示识别帧检出疑似废弃渔具 2 处，平均置信度 0.84，人工复核状态为已确认。',
    'demo://lianjiang/knowledge/huangqi-foam-detection-frame',
    9.300000,
    '{"demo":true,"quote_type":"image"}'::jsonb,
    now() - interval '3 days'
),
(
    'EVD-DEMO-002-02',
    'DEC-DEMO-002',
    2,
    'KA-DEMO-POLICY-001',
    'KAV-DEMO-POLICY-001-V1',
    'NODE-DEMO-PATROL',
    'REL-DEMO-007',
    1,
    '发现废弃渔具后应先触发岸线巡查，再根据核实结果生成打捞任务。',
    'demo://lianjiang/knowledge/marine-litter-response-guide',
    9.000000,
    '{"demo":true,"quote_type":"policy"}'::jsonb,
    now() - interval '3 days'
),
(
    'EVD-DEMO-002-03',
    'DEC-DEMO-002',
    3,
    'KA-DEMO-DATASET-001',
    'KAV-DEMO-DATASET-001-V1',
    'NODE-DEMO-UAV',
    'REL-DEMO-015',
    2,
    '多模态训练集包含无人机巡查样本，可用于扩展黄岐渔港岸线和近岸覆盖。',
    'demo://lianjiang/knowledge/coast-multimodal-dataset-v1',
    7.800000,
    '{"demo":true,"quote_type":"dataset"}'::jsonb,
    now() - interval '3 days'
)
ON CONFLICT (evidence_id) DO NOTHING;

COMMIT;

-- ---------- 校验输出 ----------
DO $$
DECLARE
    asset_cnt INTEGER;
    version_cnt INTEGER;
    ontology_cnt INTEGER;
    node_cnt INTEGER;
    relation_cnt INTEGER;
    decision_cnt INTEGER;
    evidence_cnt INTEGER;
BEGIN
    SELECT COUNT(*) INTO asset_cnt
    FROM t_knowledge_asset
    WHERE asset_id LIKE 'KA-DEMO-%';

    SELECT COUNT(*) INTO version_cnt
    FROM t_knowledge_asset_version
    WHERE version_id LIKE 'KAV-DEMO-%';

    SELECT COUNT(*) INTO ontology_cnt
    FROM t_ontology_version
    WHERE version_id LIKE 'ONT-DEMO-%';

    SELECT COUNT(*) INTO node_cnt
    FROM t_ontology_node
    WHERE node_id LIKE 'NODE-DEMO-%';

    SELECT COUNT(*) INTO relation_cnt
    FROM t_ontology_relation
    WHERE relation_id LIKE 'REL-DEMO-%';

    SELECT COUNT(*) INTO decision_cnt
    FROM t_decision_trace
    WHERE trace_id LIKE 'DEC-DEMO-%';

    SELECT COUNT(*) INTO evidence_cnt
    FROM t_decision_evidence
    WHERE evidence_id LIKE 'EVD-DEMO-%';

    RAISE NOTICE '[knowledge-demo] 资产 % 条 | 版本 % 条 | 本体 % 个 | 节点 % 个 | 关系 % 条 | 决策 % 条 | 证据 % 条',
        asset_cnt, version_cnt, ontology_cnt, node_cnt, relation_cnt, decision_cnt, evidence_cnt;
END $$;
